# Generated by Django 6.0.3 on 2026-04-18 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_oferta_ubicacion_mapa_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ofertas_fotos/')),
                ('pie', models.CharField(blank=True, max_length=200, verbose_name='Pie de foto (opcional)')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.oferta')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
