# Generated by Django 6.0.3 on 2026-04-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_configuracionplataforma_codigoverificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodigoVerificacion',
        ),
    ]
