# Generated by Django 6.0.3 on 2026-04-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_requiere_2fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardados_por', to='core.oferta')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleos_guardados', to='core.profile')),
            ],
            options={
                'ordering': ['-fecha_guardado'],
                'unique_together': {('postulante', 'oferta')},
            },
        ),
    ]
