# Generated by Django 6.0.3 on 2026-04-19 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_empleoguardado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleoDescartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarte', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descartados_por', to='core.oferta')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleos_descartados', to='core.profile')),
            ],
            options={
                'ordering': ['-fecha_descarte'],
                'unique_together': {('postulante', 'oferta')},
            },
        ),
    ]
