# Generated by Django 6.0.3 on 2026-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_empleodescartado'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferencias_etiquetas',
            field=models.TextField(blank=True, default='', help_text='Etiquetas separadas por comas', verbose_name='Preferencias de etiquetas'),
        ),
    ]
